puts "There are #{100} cars available."
puts "There are only #{30} drivers available."
puts "There will be #{100-30} empty cars today."
puts "We can transport #{30*4.0} people today."
puts "We have #{90} to carpool today."
puts "We need to put about #{90/30} in each car."